Module8 task1
htmlacademy-ecmascript/1770543-big-trip-15 pull request #14
Opened 2021-09-02 13:57 UTC by xolab

2021-09-02 19:24 UTC, ArtMan-8 requested changes

2021-09-02 19:24 UTC, ArtMan-8 commented on src/presenter/trip.js
> +    if(this._filterType !== FilterType.ERROR401) {
В таких случаях лучше использовать принцип `guard expression`
```
if(this._filterType === FilterType.ERROR401) {
     return points;
}
```
А ниже, что нужно выполнить.

2021-09-02 19:24 UTC, ArtMan-8 commented on src/presenter/trip.js
>      if(this._getPoints().length === 0) {
Точно нужны вложенные ифы?
Можно сделать плоско.

2021-09-02 19:24 UTC, ArtMan-8 commented on src/presenter/trip.js
>    _renderPointList() {
На 169 строке, нужен ли `.slice`?
Данные не мутируем, просто перебираем.

2021-09-02 19:24 UTC, ArtMan-8 commented on src/view/statistics.js
> +  [ChartTitle.MONEY]: (value, context) => `€ ${context.chart.data.datasets[0].data[context.dataIndex]}`,
Аргумент `value` не используется,
нужен ли он?

2021-09-02 19:24 UTC, ArtMan-8 commented on src/view/statistics.js
> +const chartData = {
Три этих функции можно попробовать оптимизировать, ибо почти полностью одинаковы.
Напомни на созвоне, может посмотрим.

2021-09-02 19:24 UTC, ArtMan-8 commented on src/view/statistics.js
>    });
У тебя описаны три типа, разметку можно и с генерировать )

2021-09-03 09:36 UTC, xolab commented on src/main.js
> +export { destinations };
Экспериментировал) Зато узнал, что из main экспортировать ничего нельзя! А какие  лучшие практики передавать справочные данные прямо во View минуя Presenters, так как мы же с ними ничего не делаем?

2021-09-03 09:43 UTC, xolab commented on src/view/statistics.js
> +  [ChartTitle.MONEY]: (value, context) => `€ ${context.chart.data.datasets[0].data[context.dataIndex]}`,
Нужен без него ошибка: TypeError: Cannot read property 'data' of undefined
    at MONEY (statistics.js:13)

2021-09-03 09:46 UTC, ArtMan-8 commented on src/main.js
> +export { destinations };
Что значит справочные?
Опиши кейс...
Для константы есть `constants` - их и дёргаем на прямую.

2021-09-03 09:47 UTC, xolab commented on src/presenter/trip.js
>    _renderPointList() {
Не знаю, тоже думал об этом, гл оставил как в task-manager

2021-09-03 09:50 UTC, xolab commented on src/view/statistics.js
>    });
наверное, но не знаю как, а подумать пока некогда - стараюсь обязательное успеть

2021-09-03 10:10 UTC, ArtMan-8 commented on src/view/statistics.js
>    });
Могу и до последнего дня по-мучить ))

2021-09-03 10:48 UTC, xolab commented on src/main.js
> +export { destinations };
вот, к примеру, destination. Мы их никак не обрабатываем и нигде не используем кроме EditView для справки - подстановки из них данных. Получается их надо получить из api и использовать только во EditView. Зачем их прокидывать через кучу моделей-презентеров?

2021-09-04 07:43 UTC, ArtMan-8 approved these changes

2021-09-04 07:43 UTC, ArtMan-8 commented on src/api.js
> +      url: `points/${point.id}`,
`url: '${Endpoints.POINTS}/${point.id}'`  ?

2021-09-04 07:43 UTC, merged