Module2 task1
htmlacademy-ecmascript/1770543-big-trip-15 pull request #4
Opened 2021-08-04 21:08 UTC by xolab

2021-08-05 07:40 UTC, ArtMan-8 requested changes

2021-08-05 07:40 UTC, ArtMan-8 commented on src/mock/point.js
> +let nextTime = 0;
В подвешенном состоянии не хорошо использовать. 
Смотрю, она используется внутри `generatePoint`, тогда там и стоит сделать замыкание.

2021-08-05 07:40 UTC, ArtMan-8 commented on src/mock/point.js
> +  } else {
Если в любом случае есть возврат, `else` опускается.

2021-08-05 07:40 UTC, ArtMan-8 commented on src/mock/point.js
> +const pointTypes = ['taxi', 'bus', 'train', 'ship', 'drive', 'flight', 'check-in', 'sightseeing', 'restaurant'];
`pointTypes`, `pointName`, `descriptions`, `typeOffers` - это всё константы, должны быть на верхнем уровне модуля, в соответствующей записи.

2021-08-05 07:40 UTC, ArtMan-8 commented on src/view/app-edit-point.js
> +  ${offers.length > 0 ? `
Можно не сравнивать с нулём, в тернарном выражении 1й операнд и так приводится к булеву значению.
0 - false
n - true

2021-08-05 07:40 UTC, ArtMan-8 commented on src/view/app-edit-point.js
> +            <input class="event__offer-checkbox  visually-hidden" id="event-offer-${type}-1" type="checkbox" name="event-offer-${type}" checked>
Про индексы забыл. Пока может не явно.
Но обязательно нужно добавить генерацию, сейчас или позже.

2021-08-05 07:40 UTC, ArtMan-8 commented on src/view/app-edit-point.js
> +  return `
После/перед бэктиком не пропускаем место, это учитывается, и вставляются пробельные символы, и символы переноса. При в ставке в разметку потом могут быть проблемы.

2021-08-05 07:40 UTC, ArtMan-8 commented on src/view/app-info.js
> +    if(points.length > 3) {
Вместо `if` можно использовать тернарник, в обоих случаях присваиваем что-то.

2021-08-05 07:40 UTC, ArtMan-8 commented on src/view/app-info.js
> +    let dateStart = '';
Так же короче и понятнее )
```
const dataFormat = monthStart === monthEnd ? 'DD' : 'MMM DD';
const dateStart = getDateFormate(getStartDataPoint[0].dateFrom, 'MMM DD');
const dateEnd = getDateFormate(getEndDataPoint[0].dateTo, dataFormat);
```

2021-08-05 07:40 UTC, ArtMan-8 commented on src/view/app-info.js
> +  const getInfoDates = () => {
Форматирование даты лучше вынести в отдельную функцию, может даже в утилиты.
К разметке не имеет никакого отношения.

Да и в общем, все вспомогательные функции лучше вынести.
Если они используются только здесь, то их можно оставить в этом файле, но вынести из функции генерации разметки.

2021-08-05 07:40 UTC, ArtMan-8 commented on src/view/app-list-event-item.js
> +  const getDuration = (dateStart, dateEnd) => {
Всё что относится к подготовке/форматированию данных выносим из функции создания разметки.

2021-08-05 07:40 UTC, ArtMan-8 commented on src/view/app-list-event-item.js
> +  const favoriteClassName = isFavorite ? 'event__favorite-btn--active' : '';
Это к разметке относится, это можно оставить.

2021-08-05 07:40 UTC, ArtMan-8 commented on src/view/app-list-event-item.js
> +  ${offers.length > 0 ? `
Можно не сравнивать с нулём, в тернарном выражении 1й операнд и так приводится к булеву значению.
0 - false
n - true

2021-08-05 07:40 UTC, ArtMan-8 commented on src/main.js
> +renderElement(appListEventsElement, createAppEditPointTemplate(points[0]), 'beforeend');
`beforeend` чаще используется, можно сделать параметр со значением по умолчанию.

2021-08-05 21:47 UTC, xolab commented on src/view/app-info.js
> +    let dateStart = '';
да классно!)

2021-08-05 22:34 UTC, xolab commented on src/main.js
> +renderElement(appListEventsElement, createAppEditPointTemplate(points[0]), 'beforeend');
Мне кажется, что с явно указанными значениями будет понятнее?

2021-08-06 01:09 UTC, xolab commented on src/view/app-edit-point.js
> +            <input class="event__offer-checkbox  visually-hidden" id="event-offer-${type}-1" type="checkbox" name="event-offer-${type}" checked>
Добавлю позже, когда станет понятен смысл

2021-08-06 16:24 UTC, ArtMan-8 approved these changes

2021-08-06 16:24 UTC, merged